name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Shellcheck
        run: shellcheck bin/*

  plugin-test:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: asdf-vm/actions/plugin-test@v1.0.0
        with:
          command: "xcodebuild -version"
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
